name: PR Checks
on: [push, pull_request]
jobs:
  validate-lockfile:
    name: Validate lockfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: Run Install
        run: yarn install
      - name: Check Lockfile
        run: git status --porcelain | grep "yarn.lock"

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: install
        run: yarn install --immutable
      - name: test
        run: yarn test

  lint:
    name: Run Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: install
        run: yarn install --immutable
      - name: lint
        run: yarn lint

  prettier:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: install
        run: yarn install --immutable
      - name: format-check
        run: yarn format:check
