name: PR Checks
on: [pull_request]

jobs:
  validate-lockfile:
    name: Validate lockfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      # In CI, yarn 2 automatically fails CI if lockfile will change
      - name: Run Install
        run: yarn

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: install
        run: yarn --immutable
      - name: test
        run: yarn test

  lint:
    name: Run Lints
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: install
        run: yarn --immutable
      - name: lint
        run: yarn lint

  prettier:
    name: Check Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - name: install
        run: yarn --immutable
      - name: format-check
        run: yarn format:check
