# Workflow runs after release is published in GH UI
# Currently no automated version checking
# Be sure to bump pjson version & changelog before creating a new release

name: "Publish After Release"
on:
  release:
    types: [released]
  push:
    branches:
      - "releases/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: yarn
      - run: yarn
      - run: yarn test
      - run: npm publish
        env:
          npm_config_//registry.npmjs.org/:_authToken: ${{secrets.NPM_AUTH_TOKEN}}
